server:
  port: 8083

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/microservices?createTableIfNotExist=true
    username : root
    password : root
  jpa :
    hibernate:
      ddl-auto : update
    show-sql : true


